### PR TITLE
Add hover styling management

### PR DESCRIPTION
**Pull request by maxiplay**

### CODE REVIEW

**Comment by notwaldorf** [comment]
@maxiplay Why is this needed? This is the same as saying
```css
paper-icon-button:hover {
  color: blue;
}
```

Generally, applying mixins to host isn't needed, since you get to style the host for free.

**Comment by maxiplay** [comment]
My need is I want to have the color 'blue' under all sub and sub components. 
 
But with 

    paper-icon-button:hover {
    color: blue;
    }

I  just have the style in first sub level component of my page.

How to generalize the style on hover to all paper-icon-button ?

**Comment by notwaldorf** [comment]
Ah yes, that makes sense in that case. Would you mind adding a line to the docs (in the styling section, along with all the other mixins)? Thanks!

**Comment by maxiplay** [comment]
it's done :)

**Comment by notwaldorf** [comment]
Thanks!

**Pull request merged**
